using NetCrypto;

// ============================================================
// NetCrypto Samples — BBS Signatures (selective disclosure)
// ============================================================
//
// BBS signs MANY messages with ONE signature. The holder can later
// derive a zero-knowledge proof that reveals only SOME of those
// messages; the verifier learns nothing about the hidden ones and
// never sees the original signature. This is the building block of
// selective-disclosure verifiable credentials.

// IBbsCryptoProvider is the stable interface; DefaultBbsCryptoProvider
// implements the BLS12-381-SHA-256 ciphersuite via a native library
// (zkryptium-ffi). Construct it and print which suite it runs.
var bbs = new DefaultBbsCryptoProvider();
Console.WriteLine($"Provider ciphersuite: {bbs.Ciphersuite}");

// Ciphersuite is plain metadata (it never touches the native binary), so it
// is safe to read even when BBS is unavailable. v1 supports exactly one
// BbsCiphersuite value: the draft-10 BLS12-381-SHA-256 suite.
Check(bbs.Ciphersuite == BbsCiphersuite.Bls12381Sha256,
    "the provider reports the BbsCiphersuite.Bls12381Sha256 suite");
Console.WriteLine();

// -------------------------------------------------------
// 1. Capability probe — ALWAYS check IsAvailable first
// -------------------------------------------------------
// BBS is the only NetCrypto primitive backed by a native binary, so
// it can be absent on some platforms. That is a SUPPORTED mode, not
// an error: IsAvailable never throws, and only the BBS operations
// throw BbsUnavailableException when the binary is missing.
Console.WriteLine("=== 1. Capability probe (IsAvailable) ===");
Console.WriteLine($"  IsAvailable: {bbs.IsAvailable}");

if (!bbs.IsAvailable)
{
    // Graceful-degradation path: the rest of NetCrypto (Ed25519, ECDSA,
    // AES, HKDF, ...) keeps working; an application should branch on
    // IsAvailable and simply not offer BBS features. If a BBS call is
    // made anyway, catch BbsUnavailableException — its InnerException
    // carries the original native-load error for diagnostics.
    Console.WriteLine("  Native library not found — supported BBS-absent mode.");
    Console.WriteLine("  Demonstrating the exception an unguarded Sign call produces:");
    try
    {
        bbs.Sign(new byte[32], new List<byte[]> { "hello"u8.ToArray() });
        Check(false, "Sign must throw BbsUnavailableException when unavailable");
    }
    catch (BbsUnavailableException ex)
    {
        Console.WriteLine($"  Caught BbsUnavailableException: {ex.Message}");
        Console.WriteLine($"  InnerException present (original load error): {ex.InnerException is not null}");
        Check(ex.InnerException is not null, "InnerException carries the native load failure");
    }
    Console.WriteLine();
    Console.WriteLine("Done! BBS-absent mode handled gracefully (exit 0 — this is supported).");
    return 0; // Not a failure: applications are expected to run like this.
}

// -------------------------------------------------------
// 2. Generate a BLS12-381 G2 key pair
// -------------------------------------------------------
// BBS signatures use BLS12-381 G2 keys (32-byte secret scalar,
// 96-byte G2 public key) — generated by the same DefaultKeyGenerator
// used for every other key type in NetCrypto.
Console.WriteLine("=== 2. BLS12-381 G2 key pair ===");

var keyGen = new DefaultKeyGenerator();
var keyPair = keyGen.Generate(KeyType.Bls12381G2);
Console.WriteLine($"  Private key: {keyPair.PrivateKey.Length} bytes");
Console.WriteLine($"  Public key:  {keyPair.PublicKey.Length} bytes");
Console.WriteLine();

// -------------------------------------------------------
// 3. Sign three messages with ONE signature
// -------------------------------------------------------
// Each message is an independent claim. Index ORDER matters — the
// same indices are used later to choose what to reveal.
Console.WriteLine("=== 3. Multi-message sign ===");

var messages = new List<byte[]>
{
    "name=Alice Example"u8.ToArray(),       // index 0
    "dateOfBirth=1990-01-01"u8.ToArray(),   // index 1 — will stay hidden
    "citizenship=US"u8.ToArray(),           // index 2
};

var signature = bbs.Sign(keyPair.PrivateKey, messages);
Console.WriteLine($"  Signed {messages.Count} messages -> signature of {signature.Length} bytes");
Check(signature.Length == 80, "BLS12-381-SHA-256 signature is 80 bytes");
Console.WriteLine();

// -------------------------------------------------------
// 4. Verify the signature against ALL messages
// -------------------------------------------------------
// Plain verification needs the full ordered message list — this is
// what the credential HOLDER does once, on receipt, to check the
// issuer really signed every claim.
Console.WriteLine("=== 4. Verify ===");

var valid = bbs.Verify(keyPair.PublicKey, signature, messages);
Console.WriteLine($"  Signature valid over all 3 messages: {valid}");
Check(valid, "Verify returns true for the untampered message set");
Console.WriteLine();

// -------------------------------------------------------
// 5. DeriveProof — reveal only indices 0 and 2
// -------------------------------------------------------
// The holder derives a fresh zero-knowledge proof revealing name and
// citizenship while keeping dateOfBirth hidden. The nonce binds the
// proof to one verifier interaction (the verifier's challenge), so a
// captured proof cannot be replayed elsewhere.
Console.WriteLine("=== 5. DeriveProof (selective disclosure) ===");

var revealedIndices = new List<int> { 0, 2 };
var nonce = "verifier-challenge-42"u8.ToArray();

var proof = bbs.DeriveProof(keyPair.PublicKey, signature, messages, revealedIndices, nonce);
Console.WriteLine($"  Proof: {proof.Length} bytes, reveals indices [0, 2], hides index 1");
Console.WriteLine();

// -------------------------------------------------------
// 6. VerifyProof — the verifier's side
// -------------------------------------------------------
// The verifier gets ONLY the revealed messages, their original
// indices, the proof, the issuer public key, and the nonce it
// issued. It never sees dateOfBirth or the original signature.
Console.WriteLine("=== 6. VerifyProof ===");

var revealedMessages = new List<byte[]> { messages[0], messages[2] };
var proofValid = bbs.VerifyProof(keyPair.PublicKey, proof, revealedMessages, revealedIndices, nonce);
Console.WriteLine($"  Proof valid for revealed messages: {proofValid}");
Check(proofValid, "VerifyProof returns true for honestly revealed messages");
Console.WriteLine();

// -------------------------------------------------------
// 7. Tamper detection — a forged revealed message fails
// -------------------------------------------------------
// If the holder (or anyone in transit) alters a revealed claim, the
// proof no longer matches: VerifyProof returns false rather than
// throwing, so treat the bool as the authoritative result.
Console.WriteLine("=== 7. Tampered revealed message ===");

var tampered = new List<byte[]> { messages[0], "citizenship=CA"u8.ToArray() };
var tamperedValid = bbs.VerifyProof(keyPair.PublicKey, proof, tampered, revealedIndices, nonce);
Console.WriteLine($"  Proof valid after tampering with citizenship: {tamperedValid}");
Check(!tamperedValid, "VerifyProof returns false for a tampered revealed message");
Console.WriteLine();

// -------------------------------------------------------
// 8. Header — bind issuer data the holder CANNOT drop
// -------------------------------------------------------
// The presentation header (the `nonce` above) is chosen by the HOLDER
// at derive time. The signature `header` is different: it is fixed by
// the ISSUER at sign time and committed by the signature AND every
// derived proof. Anything bound into the header — e.g. the W3C
// bbs-2023 cryptosuite binds its mandatory-disclosure group here —
// cannot be altered or dropped without verification failing.
//
// header (issuer, sign time)        != presentationHeader (holder, derive time)
Console.WriteLine("=== 8. Signature header (issuer-bound) ===");

var header = "bbs-2023:mandatory=[issuer,expiry]"u8.ToArray();

// Issuer signs WITH the header bound in.
var boundSig = bbs.Sign(keyPair.PrivateKey, messages, header);

// Verifying with the same header succeeds; a different header fails;
// and omitting the header (the default) fails — proving the header is
// genuinely committed, not ignored.
Check(bbs.Verify(keyPair.PublicKey, boundSig, messages, header),
    "Verify succeeds with the header the issuer bound");
Check(!bbs.Verify(keyPair.PublicKey, boundSig, messages, "different-header"u8.ToArray()),
    "Verify fails when the header differs from the one signed");
Check(!bbs.Verify(keyPair.PublicKey, boundSig, messages),
    "Verify fails when the header is omitted (default empty) for a header-bound signature");

// The header flows through selective disclosure too: derive a proof
// under the header, then a verifier checks it with the SAME header.
var boundProof = bbs.DeriveProof(
    keyPair.PublicKey, boundSig, messages, revealedIndices, nonce, header);
Check(bbs.VerifyProof(keyPair.PublicKey, boundProof, revealedMessages, revealedIndices, nonce, header),
    "VerifyProof succeeds with the matching presentation header and header");
Check(!bbs.VerifyProof(keyPair.PublicKey, boundProof, revealedMessages, revealedIndices, nonce, "wrong-header"u8.ToArray()),
    "VerifyProof fails when the header differs from the one bound at derive time");
Console.WriteLine("  Header is committed by both Verify and the derived proof.");
Console.WriteLine();

Console.WriteLine("Done! All BBS examples completed successfully.");
return 0;

// Tiny expectation helper: print the outcome and abort with a non-zero
// exit code on the first failed expectation, so CI can trust exit 0.
static void Check(bool condition, string what)
{
    Console.WriteLine($"  [{(condition ? "ok" : "FAIL")}] {what}");
    if (!condition) Environment.Exit(1);
}
